#!/usr/bin/env bash
# Script for configure and replace the localhost and facebook IP.

if [ "$EUID" -ne 0 ]; then
    echo "run it as root"
    exit
fi

echo "/localhost/c\127.0.0.2 localhost" /etc/hosts
echo "/facebook.com/c\8.8.8.8 facebook.com" /etc/hosts
