#!/usr/bin/env bash
# Script for configure and replace the localhost and facebook IP.

if [ "$EUID" -ne 0 ]; then
    echo "run it as root"
    exit
fi

echo '127.0.0.2       localhost/' /etc/hosts
echo "8.8.8.8        facebook.com" >> /etc/hosts